module.exports = [{
	src: 'templates/bootstrap',
	dest: 'bootstrap'
}, {
	src: 'templates/assets',
	dest: 'assets'
}, {
	src: 'templates/index.html',
	dest: 'index.html'
}, {
	src: 'templates/_package.json',
	dest: 'package.json'
}, {
	src: 'templates/component.json',
	dest: 'component.json'
}, {
	src: 'templates/gitignore',
	dest: '.gitignore'
}, {
	src: 'templates/Gruntfile.js',
	dest: 'Gruntfile.js'
}, {
	src: 'templates/jshintrc',
	dest: '.jshintrc'
}, {
	src: 'templates/bowerrc',
	dest: '.bowerrc'	
}, {
	src: 'templates/robots.txt',
	dest: 'robots.txt'
}];